### ISSUE TITLE
Crash on animated reload

### ISSUE THREAD

**Issue by aminiz2** [darrarski/DRCollectionViewTableLayout-iOS#6]
The following causes a crash: 

> ```
> [self.collectionView performBatchUpdates:^{
>     [self.collectionView reloadData];
> } completion:^(BOOL finished) {}];
> ```

Here is the log: 

> **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (8) must be equal to the number of items contained in that section before the update (6), plus or minus the number of items inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'

If I do not animate the reload and simply call 

> [self.collectionView reloadData];

then, there is no crash.

**Comment by darrarski** [comment]
More details will be needed to reproduce the crash. Especially, what changes you made to data source.
